### ISSUE TITLE
请问是在哪一步把config.session配置的store加进去的?

### ISSUE THREAD

**Issue by jackhutu** [sunshinexb/egg-generic-session#1]
比如要将session存入redis ,  koa-generic-session配置中有一个store项, 可以将redis实例传入, 那在egg中, 难道要在config中就将redis实例传入吗, 还是在其它步骤传入?

**Comment by jackhutu** [comment]
哦, 只要配置app.sessionStore 就行了.

**Comment by jackhutu** [comment]
但是为什么不能将sessionId存在redis中呢?

**Comment by sunshinexb** [comment]
这个项目当时是为了保存session进入redis中写的，现在官方的egg-session已经支持，所有直接使用egg-session就可以。
